name: universal_sequencer
description: Native AOT compiled universal math sequencer.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image: ^4.1.3
  share_plus: ^7.2.1
  path_provider: ^2.1.1

flutter:
  uses-material-design: true
